name: airscaper
description: Escame game with QR codes

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.1.1+2

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

  # Service locator / dependency injection
  get_it: ^5.0.0

  # State management
  cubit: ^0.1.2
  flutter_cubit: ^0.1.1
  flutter_bloc: ^6.0.5
  hydrated_bloc: ^6.0.2
  shared_preferences: ^0.5.12+4

  # I18n
  flutter_localizations:
    sdk: flutter
  intl: ^0.16.1
  flutter_i18n: ^0.20.1


  # Network
  http: ^0.12.0+4

  # UI components
  progress_indicators: ^0.1.4
  page_view_indicators: ^1.3.0 # PageView component
  photo_view: ^0.10.1 # Component that allow zoom into image

  # Device helpers
  barcode_scan: ^3.0.1 # Launch barcode scanning screen (MOBILE ONLY)
  url_launcher: ^5.5.0 # Launch app or web page from URL
  flutter_keyboard_visibility: ^3.2.1 # Manage keyboard visibility listeners

  # Image management
  image: ^2.1.18 # to manage image compression
  flutter_svg: ^0.19.0 # To interpret SVG

  # Graph dependencies
  graphview: ^0.6.1

  # Dart code helpers
  catcher: ^0.3.11 # Exception management
  equatable: ^1.0.1 # Object comparison
  dartz: ^0.9.1 # Functional programming functions
  quiver: ^2.0.5 # Helpers function for collection, strings etc.
  supercharged: ^1.11.1 # Provides helpers function in Kotlin style
  enum_to_string: ^1.0.8 # Transform enum object to string
  json_annotation: ^3.1.0 # Give annotation to simplify data model JSON parsing
  email_validator: ^1.0.6 # Used to validate email string

dev_dependencies:
  flutter_test:
    sdk: flutter

  # To build with build_runner : flutter packages pub run build_runner build
  # To watch with build_runner : flutter packages pub run build_runner watch
  build_runner: ^1.10.0

  # Used with build_runner to generate JSON parsing functions for data model class
  # annotated with json_annotation
  json_serializable: ^3.5.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/i18n/
    - assets/scenarios/
    - assets/images/
    - assets/images/common/
    - assets/images/tutorial/
    - assets/images/tresor/
    - assets/images/tresor/transparent/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
